package com.LiferayEnEspanol.booking.model.impl;

import com.LiferayEnEspanol.booking.model.MeetingRoom;
import com.LiferayEnEspanol.booking.service.MeetingRoomLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the MeetingRoom service. Represents a row in the &quot;LiferayEnEspanol_MeetingRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetingRoomImpl}.
 * </p>
 *
 * @author Jesus Flores
 * @see MeetingRoomImpl
 * @see com.LiferayEnEspanol.booking.model.MeetingRoom
 * @generated
 */
public abstract class MeetingRoomBaseImpl extends MeetingRoomModelImpl
    implements MeetingRoom {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a meeting room model instance should use the {@link MeetingRoom} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MeetingRoomLocalServiceUtil.addMeetingRoom(this);
        } else {
            MeetingRoomLocalServiceUtil.updateMeetingRoom(this);
        }
    }
}
