/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.LiferayEnEspanol.booking.service.base;

import com.LiferayEnEspanol.booking.model.MeetingRoom;
import com.LiferayEnEspanol.booking.service.MeetingRoomService;
import com.LiferayEnEspanol.booking.service.persistence.MeetingRoomPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the meeting room remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.LiferayEnEspanol.booking.service.impl.MeetingRoomServiceImpl}.
 * </p>
 *
 * @author Jesus Flores
 * @see com.LiferayEnEspanol.booking.service.impl.MeetingRoomServiceImpl
 * @see com.LiferayEnEspanol.booking.service.MeetingRoomServiceUtil
 * @generated
 */
public abstract class MeetingRoomServiceBaseImpl extends BaseServiceImpl
	implements MeetingRoomService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.LiferayEnEspanol.booking.service.MeetingRoomServiceUtil} to access the meeting room remote service.
	 */

	/**
	 * Returns the meeting room local service.
	 *
	 * @return the meeting room local service
	 */
	public com.LiferayEnEspanol.booking.service.MeetingRoomLocalService getMeetingRoomLocalService() {
		return meetingRoomLocalService;
	}

	/**
	 * Sets the meeting room local service.
	 *
	 * @param meetingRoomLocalService the meeting room local service
	 */
	public void setMeetingRoomLocalService(
		com.LiferayEnEspanol.booking.service.MeetingRoomLocalService meetingRoomLocalService) {
		this.meetingRoomLocalService = meetingRoomLocalService;
	}

	/**
	 * Returns the meeting room remote service.
	 *
	 * @return the meeting room remote service
	 */
	public com.LiferayEnEspanol.booking.service.MeetingRoomService getMeetingRoomService() {
		return meetingRoomService;
	}

	/**
	 * Sets the meeting room remote service.
	 *
	 * @param meetingRoomService the meeting room remote service
	 */
	public void setMeetingRoomService(
		com.LiferayEnEspanol.booking.service.MeetingRoomService meetingRoomService) {
		this.meetingRoomService = meetingRoomService;
	}

	/**
	 * Returns the meeting room persistence.
	 *
	 * @return the meeting room persistence
	 */
	public MeetingRoomPersistence getMeetingRoomPersistence() {
		return meetingRoomPersistence;
	}

	/**
	 * Sets the meeting room persistence.
	 *
	 * @param meetingRoomPersistence the meeting room persistence
	 */
	public void setMeetingRoomPersistence(
		MeetingRoomPersistence meetingRoomPersistence) {
		this.meetingRoomPersistence = meetingRoomPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return MeetingRoom.class;
	}

	protected String getModelClassName() {
		return MeetingRoom.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = meetingRoomPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.LiferayEnEspanol.booking.service.MeetingRoomLocalService.class)
	protected com.LiferayEnEspanol.booking.service.MeetingRoomLocalService meetingRoomLocalService;
	@BeanReference(type = com.LiferayEnEspanol.booking.service.MeetingRoomService.class)
	protected com.LiferayEnEspanol.booking.service.MeetingRoomService meetingRoomService;
	@BeanReference(type = MeetingRoomPersistence.class)
	protected MeetingRoomPersistence meetingRoomPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private MeetingRoomServiceClpInvoker _clpInvoker = new MeetingRoomServiceClpInvoker();
}