/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.LiferayEnEspanol.booking.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MeetingRoom service. Represents a row in the &quot;LiferayEnEspanol_MeetingRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.LiferayEnEspanol.booking.model.impl.MeetingRoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.LiferayEnEspanol.booking.model.impl.MeetingRoomImpl}.
 * </p>
 *
 * @author Jesus Flores
 * @see MeetingRoom
 * @see com.LiferayEnEspanol.booking.model.impl.MeetingRoomImpl
 * @see com.LiferayEnEspanol.booking.model.impl.MeetingRoomModelImpl
 * @generated
 */
public interface MeetingRoomModel extends BaseModel<MeetingRoom>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a meeting room model instance should use the {@link MeetingRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this meeting room.
	 *
	 * @return the primary key of this meeting room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this meeting room.
	 *
	 * @param primaryKey the primary key of this meeting room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the meeting room ID of this meeting room.
	 *
	 * @return the meeting room ID of this meeting room
	 */
	public long getMeetingRoomId();

	/**
	 * Sets the meeting room ID of this meeting room.
	 *
	 * @param meetingRoomId the meeting room ID of this meeting room
	 */
	public void setMeetingRoomId(long meetingRoomId);

	/**
	 * Returns the group ID of this meeting room.
	 *
	 * @return the group ID of this meeting room
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this meeting room.
	 *
	 * @param groupId the group ID of this meeting room
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this meeting room.
	 *
	 * @return the company ID of this meeting room
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this meeting room.
	 *
	 * @param companyId the company ID of this meeting room
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this meeting room.
	 *
	 * @return the user ID of this meeting room
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this meeting room.
	 *
	 * @param userId the user ID of this meeting room
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this meeting room.
	 *
	 * @return the user uuid of this meeting room
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this meeting room.
	 *
	 * @param userUuid the user uuid of this meeting room
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this meeting room.
	 *
	 * @return the user name of this meeting room
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this meeting room.
	 *
	 * @param userName the user name of this meeting room
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this meeting room.
	 *
	 * @return the create date of this meeting room
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this meeting room.
	 *
	 * @param createDate the create date of this meeting room
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this meeting room.
	 *
	 * @return the modified date of this meeting room
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this meeting room.
	 *
	 * @param modifiedDate the modified date of this meeting room
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this meeting room.
	 *
	 * @return the name of this meeting room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this meeting room.
	 *
	 * @param name the name of this meeting room
	 */
	public void setName(String name);

	/**
	 * Returns the code of this meeting room.
	 *
	 * @return the code of this meeting room
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this meeting room.
	 *
	 * @param code the code of this meeting room
	 */
	public void setCode(String code);

	/**
	 * Returns the capacity of this meeting room.
	 *
	 * @return the capacity of this meeting room
	 */
	public int getCapacity();

	/**
	 * Sets the capacity of this meeting room.
	 *
	 * @param capacity the capacity of this meeting room
	 */
	public void setCapacity(int capacity);

	/**
	 * Returns the location of this meeting room.
	 *
	 * @return the location of this meeting room
	 */
	public boolean getLocation();

	/**
	 * Returns <code>true</code> if this meeting room is location.
	 *
	 * @return <code>true</code> if this meeting room is location; <code>false</code> otherwise
	 */
	public boolean isLocation();

	/**
	 * Sets whether this meeting room is location.
	 *
	 * @param location the location of this meeting room
	 */
	public void setLocation(boolean location);

	/**
	 * Returns the active of this meeting room.
	 *
	 * @return the active of this meeting room
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this meeting room is active.
	 *
	 * @return <code>true</code> if this meeting room is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this meeting room is active.
	 *
	 * @param active the active of this meeting room
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.LiferayEnEspanol.booking.model.MeetingRoom meetingRoom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.LiferayEnEspanol.booking.model.MeetingRoom> toCacheModel();

	@Override
	public com.LiferayEnEspanol.booking.model.MeetingRoom toEscapedModel();

	@Override
	public com.LiferayEnEspanol.booking.model.MeetingRoom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}